import { gql } from "~/gql";

// Operation names are global across erxes; keep the plugin prefix. gql() is
// generated by codegen — write documents as static strings (no `${}`), and
// let Apollo hooks infer their types from the document.
export const STATUS_QUERY = gql(`
  query __camel__Status {
    __camel__Status {
      plugin
      version
      subdomain
      userId
      userEmail
    }
  }
`);
