import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const templatesDir = fileURLToPath(new URL("../templates/", import.meta.url));
const packageJson = fileURLToPath(new URL("../package.json", import.meta.url));
const outputFile = fileURLToPath(new URL("../src/templates.generated.ts", import.meta.url));

const { version } = JSON.parse(readFileSync(packageJson, "utf8")) as { version: string };

const entries: [string, string][] = [];
for (const entry of readdirSync(templatesDir, { recursive: true, withFileTypes: true })) {
  if (!entry.isFile()) continue;
  const key = join(relative(templatesDir, entry.parentPath), entry.name)
    .split(sep)
    .join("/");
  entries.push([key, readFileSync(join(entry.parentPath, entry.name), "utf8")]);
}
entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const body = `// Generated by scripts/embed-templates.ts — do not edit.
export const VERSION = ${JSON.stringify(version)};
export const TEMPLATES: Record<string, string> = {
${entries.map(([key, content]) => `  ${JSON.stringify(key)}: ${JSON.stringify(content)},`).join("\n")}
};
`;

writeFileSync(outputFile, body);
console.log(`Embedded ${entries.length} templates into src/templates.generated.ts`);
